// Generated by scripts/build-docs-nav.mjs. Do not edit manually.

import type { DefaultTheme } from 'vitepress'

export const sidebar: DefaultTheme.SidebarItem[] = 
[
  {
    "text": "Introduction",
    "link": "/"
  },
  {
    "text": "Installation",
    "link": "/installation",
    "items": [
      {
        "text": "In the HarborClient monorepo",
        "link": "/installation#in-the-harborclient-monorepo"
      },
      {
        "text": "As a published package",
        "link": "/installation#as-a-published-package"
      }
    ],
    "collapsed": false
  },
  {
    "text": "Package layout",
    "link": "/package-layout"
  },
  {
    "text": "Imports and exports",
    "link": "/imports-and-exports",
    "items": [
      {
        "text": "Module imports",
        "link": "/imports-and-exports#module-imports"
      },
      {
        "text": "Portable HarborClient files",
        "link": "/imports-and-exports#portable-harborclient-files",
        "items": [
          {
            "text": "Discriminators",
            "link": "/imports-and-exports#discriminators"
          },
          {
            "text": "Parse and stringify",
            "link": "/imports-and-exports#parse-and-stringify"
          },
          {
            "text": "Related helpers",
            "link": "/imports-and-exports#related-helpers"
          }
        ],
        "collapsed": false
      }
    ],
    "collapsed": false
  },
  {
    "text": "Request runner",
    "link": "/request-runner"
  },
  {
    "text": "Scripting",
    "link": "/scripting"
  },
  {
    "text": "Types and IPC contract",
    "link": "/types-and-ipc-contract"
  },
  {
    "text": "Development",
    "link": "/development"
  }
]
