// Generated by scripts/build-docs-nav.mjs. Do not edit manually.

import type { DefaultTheme } from 'vitepress'

export const sidebar: DefaultTheme.SidebarItem[] = 
[
  {
    "text": "Introduction",
    "link": "/"
  },
  {
    "text": "Install",
    "link": "/install",
    "items": [
      {
        "text": "Skeleton plugin",
        "link": "/install#skeleton-plugin"
      },
      {
        "text": "Development",
        "link": "/install#development"
      },
      {
        "text": "Building",
        "link": "/install#building"
      }
    ],
    "collapsed": false
  },
  {
    "text": "Quick start",
    "link": "/usage",
    "items": [
      {
        "text": "Renderer entry",
        "link": "/usage#renderer-entry"
      },
      {
        "text": "Main entry",
        "link": "/usage#main-entry"
      },
      {
        "text": "Utility imports",
        "link": "/usage#utility-imports"
      },
      {
        "text": "Plugin build and tooling baseline",
        "link": "/usage#plugin-build-and-tooling-baseline"
      }
    ],
    "collapsed": false
  },
  {
    "text": "Architecture",
    "link": "/architecture",
    "items": [
      {
        "text": "Two runtimes",
        "link": "/architecture#two-runtimes"
      },
      {
        "text": "Lifecycle",
        "link": "/architecture#lifecycle"
      }
    ],
    "collapsed": false
  },
  {
    "text": "Manifest",
    "link": "/manifest",
    "items": [
      {
        "text": "Package layout",
        "link": "/manifest#package-layout"
      },
      {
        "text": "Fields",
        "link": "/manifest#fields"
      },
      {
        "text": "Plugin metadata",
        "link": "/manifest#plugin-metadata"
      },
      {
        "text": "Permissions",
        "link": "/manifest#permissions"
      },
      {
        "text": "Theme plugins",
        "link": "/manifest#theme-plugins"
      },
      {
        "text": "Contribution types",
        "link": "/manifest#contribution-types"
      }
    ],
    "collapsed": false
  },
  {
    "text": "Building",
    "link": "/building",
    "items": [
      {
        "text": "Recommended project setup",
        "link": "/building#recommended-project-setup"
      },
      {
        "text": "Build with pnpm",
        "link": "/building#build-with-pnpm"
      },
      {
        "text": "Main entry",
        "link": "/building#main-entry"
      },
      {
        "text": "Serve or package the plugin",
        "link": "/building#serve-or-package-the-plugin"
      }
    ],
    "collapsed": false
  },
  {
    "text": "Signing",
    "link": "/signing",
    "items": [
      {
        "text": "Generate a key pair",
        "link": "/signing#generate-a-key-pair"
      },
      {
        "text": "Sign a plugin directory",
        "link": "/signing#sign-a-plugin-directory"
      },
      {
        "text": "Verify a plugin directory",
        "link": "/signing#verify-a-plugin-directory"
      },
      {
        "text": "Programmatic API",
        "link": "/signing#programmatic-api"
      },
      {
        "text": "signature.json format",
        "link": "/signing#signaturejson-format"
      },
      {
        "text": "Marketplace plugins",
        "link": "/signing#marketplace-plugins"
      }
    ],
    "collapsed": false
  },
  {
    "text": "Dev workflow",
    "link": "/dev-workflow",
    "items": [
      {
        "text": "Load unpacked",
        "link": "/dev-workflow#load-unpacked"
      },
      {
        "text": "Hot reload",
        "link": "/dev-workflow#hot-reload"
      },
      {
        "text": "Recommended dev workflow",
        "link": "/dev-workflow#recommended-dev-workflow"
      },
      {
        "text": "Load unpacked at startup (optional)",
        "link": "/dev-workflow#load-unpacked-at-startup-optional"
      },
      {
        "text": "Unpacked vs installed",
        "link": "/dev-workflow#unpacked-vs-installed"
      },
      {
        "text": "Host IPC (development)",
        "link": "/dev-workflow#host-ipc-development"
      }
    ],
    "collapsed": false
  },
  {
    "text": "API",
    "link": "/api/",
    "collapsed": false,
    "items": [
      {
        "text": "UI",
        "link": "/api/ui"
      },
      {
        "text": "Actions",
        "link": "/api/actions"
      },
      {
        "text": "Themes",
        "link": "/api/themes"
      },
      {
        "text": "Commands",
        "link": "/api/commands"
      },
      {
        "text": "Storage",
        "link": "/api/storage"
      },
      {
        "text": "Database",
        "link": "/api/database"
      },
      {
        "text": "FS",
        "link": "/api/fs"
      },
      {
        "text": "HTTP",
        "link": "/api/http"
      },
      {
        "text": "IPC",
        "link": "/api/ipc"
      },
      {
        "text": "Host",
        "link": "/api/host"
      },
      {
        "text": "Imports",
        "link": "/api/imports"
      },
      {
        "text": "MCP",
        "link": "/api/mcp"
      },
      {
        "text": "Live servers",
        "link": "/api/liveServers"
      },
      {
        "text": "Live pages",
        "link": "/api/livePages"
      },
      {
        "text": "Live page",
        "link": "/api/livePage"
      },
      {
        "text": "AI",
        "link": "/api/ai"
      },
      {
        "text": "Server",
        "link": "/api/server"
      },
      {
        "text": "Scripts",
        "link": "/api/scripts"
      },
      {
        "text": "pluginId",
        "link": "/api/pluginId"
      },
      {
        "text": "React",
        "link": "/api/react"
      }
    ]
  },
  {
    "text": "Examples",
    "link": "/examples/",
    "collapsed": false,
    "items": [
      {
        "text": "Request logger",
        "link": "/examples/request-logger"
      },
      {
        "text": "Baseline tests",
        "link": "/examples/baseline-tests"
      },
      {
        "text": "Trace correlation",
        "link": "/examples/trace-correlation"
      },
      {
        "text": "Production guard",
        "link": "/examples/production-guard"
      },
      {
        "text": "Request audit tab",
        "link": "/examples/request-audit-tab"
      },
      {
        "text": "Solarized theme",
        "link": "/examples/solarized-theme"
      },
      {
        "text": "Import handler",
        "link": "/examples/import-handler"
      },
      {
        "text": "MCP client server",
        "link": "/examples/mcp-client-server"
      },
      {
        "text": "Chat pointers",
        "link": "/examples/chat-pointers"
      },
      {
        "text": "AI instructions and turn hooks",
        "link": "/examples/ai-instructions-turn-hooks"
      },
      {
        "text": "Sidebar replacement tree",
        "link": "/examples/sidebar-replacement-tree"
      }
    ]
  },
  {
    "text": "Marketplace",
    "link": "/marketplace",
    "items": [
      {
        "text": "Requirements",
        "link": "/marketplace#requirements"
      },
      {
        "text": "Catalog entry fields",
        "link": "/marketplace#catalog-entry-fields"
      },
      {
        "text": "Theme listings",
        "link": "/marketplace#theme-listings"
      }
    ],
    "collapsed": false
  },
  {
    "text": "API Index",
    "link": "/api-index"
  }
]
