import { config, library } from '@fortawesome/fontawesome-svg-core';
import {
  faAngleLeft,
  faBars,
  faChevronDown,
  faChevronRight,
  faCircleCheck,
  faClockRotateLeft,
  faCode,
  faDatabase,
  faFloppyDisk,
  faGear,
  faGripVertical,
  faKeyboard,
  faMinus,
  faPlus,
  faPuzzlePiece,
  faRobot,
  faServer,
  faTableColumns,
  faWindowMaximize,
  faXmark
} from '@fortawesome/free-solid-svg-icons';

library.add(
  faAngleLeft,
  faXmark,
  faPlus,
  faBars,
  faTableColumns,
  faChevronDown,
  faChevronRight,
  faClockRotateLeft,
  faCircleCheck,
  faCode,
  faDatabase,
  faFloppyDisk,
  faGear,
  faGripVertical,
  faKeyboard,
  faRobot,
  faMinus,
  faPuzzlePiece,
  faServer,
  faWindowMaximize
);
config.autoAddCss = false;

export {
  faAngleLeft,
  faBars,
  faChevronDown,
  faChevronRight,
  faCircleCheck,
  faClockRotateLeft,
  faCode,
  faDatabase,
  faFloppyDisk,
  faGear,
  faGripVertical,
  faKeyboard,
  faMinus,
  faPlus,
  faPuzzlePiece,
  faRobot,
  faServer,
  faTableColumns,
  faWindowMaximize,
  faXmark
};
