// Generated by scripts/build-docs-nav.mjs. Do not edit manually.

import type { DefaultTheme } from 'vitepress'

export const sidebar: DefaultTheme.SidebarItem[] = 
[
  {
    "text": "Team Hub",
    "link": "/"
  },
  {
    "text": "Prerequisites",
    "link": "/prerequisites"
  },
  {
    "text": "Setup",
    "link": "/setup"
  },
  {
    "text": "Configuration",
    "link": "/configuration",
    "items": [
      {
        "text": "Environment variable interpolation",
        "link": "/configuration#environment-variable-interpolation"
      },
      {
        "text": "Sections overview",
        "link": "/configuration#sections-overview"
      },
      {
        "text": "server",
        "link": "/configuration#server"
      },
      {
        "text": "db",
        "link": "/configuration#db"
      },
      {
        "text": "redis",
        "link": "/configuration#redis"
      },
      {
        "text": "logging",
        "link": "/configuration#logging"
      },
      {
        "text": "metrics",
        "link": "/configuration#metrics"
      },
      {
        "text": "storage",
        "link": "/configuration#storage"
      },
      {
        "text": "llm",
        "link": "/configuration#llm"
      },
      {
        "text": "plugins",
        "link": "/configuration#plugins"
      },
      {
        "text": "docs",
        "link": "/configuration#docs"
      },
      {
        "text": "AI chat stream proxies",
        "link": "/configuration#ai-chat-stream-proxies"
      },
      {
        "text": "multitenancy",
        "link": "/configuration#multitenancy"
      },
      {
        "text": "collaboration",
        "link": "/configuration#collaboration"
      },
      {
        "text": "Docker environment variables",
        "link": "/configuration#docker-environment-variables"
      },
      {
        "text": "Related docs",
        "link": "/configuration#related-docs"
      }
    ],
    "collapsed": false
  },
  {
    "text": "Deploy",
    "link": "/deploy/"
  },
  {
    "text": "Authentication",
    "link": "/auth"
  },
  {
    "text": "LLM",
    "link": "/llm",
    "items": [
      {
        "text": "Configuration",
        "link": "/llm#configuration"
      },
      {
        "text": "User access",
        "link": "/llm#user-access"
      },
      {
        "text": "Agent loop",
        "link": "/llm#agent-loop"
      },
      {
        "text": "Monthly limits",
        "link": "/llm#monthly-limits"
      },
      {
        "text": "Usage logging",
        "link": "/llm#usage-logging"
      },
      {
        "text": "Endpoints",
        "link": "/llm#endpoints"
      }
    ],
    "collapsed": false
  },
  {
    "text": "AI chat stream",
    "link": "/ai-chat-stream",
    "items": [
      {
        "text": "Wire format",
        "link": "/ai-chat-stream#wire-format"
      },
      {
        "text": "Event catalog",
        "link": "/ai-chat-stream#event-catalog"
      },
      {
        "text": "Terminal semantics",
        "link": "/ai-chat-stream#terminal-semantics"
      },
      {
        "text": "Tool ownership",
        "link": "/ai-chat-stream#tool-ownership"
      },
      {
        "text": "Iteration limits",
        "link": "/ai-chat-stream#iteration-limits"
      },
      {
        "text": "JSON step endpoint",
        "link": "/ai-chat-stream#json-step-endpoint"
      },
      {
        "text": "Reverse proxies",
        "link": "/ai-chat-stream#reverse-proxies"
      },
      {
        "text": "Related docs",
        "link": "/ai-chat-stream#related-docs"
      }
    ],
    "collapsed": false
  },
  {
    "text": "CLI",
    "link": "/cli",
    "items": [
      {
        "text": "Global options",
        "link": "/cli#global-options"
      },
      {
        "text": "Commands overview",
        "link": "/cli#commands-overview"
      },
      {
        "text": "start",
        "link": "/cli#start"
      },
      {
        "text": "migrate",
        "link": "/cli#migrate"
      },
      {
        "text": "migrate-avatars",
        "link": "/cli#migrate-avatars"
      },
      {
        "text": "collection list",
        "link": "/cli#collection-list"
      },
      {
        "text": "llm list",
        "link": "/cli#llm-list"
      },
      {
        "text": "tenant",
        "link": "/cli#tenant"
      },
      {
        "text": "user",
        "link": "/cli#user"
      },
      {
        "text": "user token",
        "link": "/cli#user-token"
      },
      {
        "text": "Examples",
        "link": "/cli#examples"
      }
    ],
    "collapsed": false
  },
  {
    "text": "API Endpoints",
    "link": "/endpoints",
    "items": [
      {
        "text": "Overview",
        "link": "/endpoints#overview"
      },
      {
        "text": "Conventions",
        "link": "/endpoints#conventions",
        "items": [
          {
            "text": "Timestamps",
            "link": "/endpoints#timestamps"
          },
          {
            "text": "Errors",
            "link": "/endpoints#errors"
          },
          {
            "text": "Empty responses",
            "link": "/endpoints#empty-responses"
          },
          {
            "text": "Shared types",
            "link": "/endpoints#shared-types"
          }
        ],
        "collapsed": false
      },
      {
        "text": "Health",
        "link": "/endpoints#health",
        "items": [
          {
            "text": "GET /health",
            "link": "/endpoints#get-health"
          },
          {
            "text": "GET /healthz",
            "link": "/endpoints#get-healthz"
          },
          {
            "text": "GET /readyz",
            "link": "/endpoints#get-readyz"
          },
          {
            "text": "GET /metrics",
            "link": "/endpoints#get-metrics"
          },
          {
            "text": "GET /join",
            "link": "/endpoints#get-join"
          }
        ],
        "collapsed": false
      },
      {
        "text": "Authentication",
        "link": "/endpoints#authentication",
        "items": [
          {
            "text": "GET /auth/session",
            "link": "/endpoints#get-authsession"
          },
          {
            "text": "PUT /auth/profile/avatar",
            "link": "/endpoints#put-authprofileavatar"
          },
          {
            "text": "GET /auth/users/:id/avatar",
            "link": "/endpoints#get-authusersidavatar"
          },
          {
            "text": "GET /auth/hub/avatar",
            "link": "/endpoints#get-authhubavatar"
          }
        ],
        "collapsed": false
      },
      {
        "text": "Administration",
        "link": "/endpoints#administration",
        "items": [
          {
            "text": "GET /admin/users",
            "link": "/endpoints#get-adminusers"
          },
          {
            "text": "PUT /admin/users/:id",
            "link": "/endpoints#put-adminusersid"
          },
          {
            "text": "DELETE /admin/users/:id",
            "link": "/endpoints#delete-adminusersid"
          },
          {
            "text": "PUT /admin/hub/avatar",
            "link": "/endpoints#put-adminhubavatar"
          },
          {
            "text": "POST /admin/users",
            "link": "/endpoints#post-adminusers"
          },
          {
            "text": "GET /admin/tokens",
            "link": "/endpoints#get-admintokens"
          },
          {
            "text": "POST /admin/users/:id/tokens",
            "link": "/endpoints#post-adminusersidtokens"
          },
          {
            "text": "DELETE /admin/tokens/:id",
            "link": "/endpoints#delete-admintokensid"
          },
          {
            "text": "GET /admin/collections",
            "link": "/endpoints#get-admincollections"
          },
          {
            "text": "PUT /admin/collections/:id",
            "link": "/endpoints#put-admincollectionsid"
          },
          {
            "text": "DELETE /admin/collections/:id",
            "link": "/endpoints#delete-admincollectionsid"
          },
          {
            "text": "GET /admin/collections/:collectionId/documents",
            "link": "/endpoints#get-admincollectionscollectioniddocuments"
          },
          {
            "text": "GET /admin/environments",
            "link": "/endpoints#get-adminenvironments"
          },
          {
            "text": "PUT /admin/environments/:id",
            "link": "/endpoints#put-adminenvironmentsid"
          },
          {
            "text": "DELETE /admin/environments/:id",
            "link": "/endpoints#delete-adminenvironmentsid"
          },
          {
            "text": "GET /admin/snippets",
            "link": "/endpoints#get-adminsnippets"
          },
          {
            "text": "PUT /admin/snippets/:id",
            "link": "/endpoints#put-adminsnippetsid"
          },
          {
            "text": "DELETE /admin/snippets/:id",
            "link": "/endpoints#delete-adminsnippetsid"
          },
          {
            "text": "GET /admin/llm/models",
            "link": "/endpoints#get-adminllmmodels"
          },
          {
            "text": "POST /admin/config/reload",
            "link": "/endpoints#post-adminconfigreload"
          }
        ],
        "collapsed": false
      },
      {
        "text": "Collections",
        "link": "/endpoints#collections",
        "items": [
          {
            "text": "GET /collections",
            "link": "/endpoints#get-collections"
          },
          {
            "text": "POST /collections",
            "link": "/endpoints#post-collections"
          },
          {
            "text": "PUT /collections/:id",
            "link": "/endpoints#put-collectionsid"
          },
          {
            "text": "DELETE /collections/:id",
            "link": "/endpoints#delete-collectionsid"
          }
        ],
        "collapsed": false
      },
      {
        "text": "Environments",
        "link": "/endpoints#environments",
        "items": [
          {
            "text": "GET /environments",
            "link": "/endpoints#get-environments"
          },
          {
            "text": "POST /environments",
            "link": "/endpoints#post-environments"
          },
          {
            "text": "PUT /environments/:id",
            "link": "/endpoints#put-environmentsid"
          },
          {
            "text": "DELETE /environments/:id",
            "link": "/endpoints#delete-environmentsid"
          }
        ],
        "collapsed": false
      },
      {
        "text": "Snippets",
        "link": "/endpoints#snippets",
        "items": [
          {
            "text": "GET /snippets",
            "link": "/endpoints#get-snippets"
          },
          {
            "text": "POST /snippets",
            "link": "/endpoints#post-snippets"
          },
          {
            "text": "PUT /snippets/:id",
            "link": "/endpoints#put-snippetsid"
          },
          {
            "text": "DELETE /snippets/:id",
            "link": "/endpoints#delete-snippetsid"
          }
        ],
        "collapsed": false
      },
      {
        "text": "Live Servers and Live Pages",
        "link": "/endpoints#live-servers-and-live-pages",
        "items": [
          {
            "text": "GET /live-servers and GET /live-pages",
            "link": "/endpoints#get-live-servers-and-get-live-pages"
          },
          {
            "text": "POST /live-servers",
            "link": "/endpoints#post-live-servers"
          },
          {
            "text": "POST /live-pages",
            "link": "/endpoints#post-live-pages"
          },
          {
            "text": "PUT /live-servers/:id and PUT /live-pages/:id",
            "link": "/endpoints#put-live-serversid-and-put-live-pagesid"
          },
          {
            "text": "DELETE /live-servers/:id and DELETE /live-pages/:id",
            "link": "/endpoints#delete-live-serversid-and-delete-live-pagesid"
          },
          {
            "text": "GET /collections/:collectionId/folders",
            "link": "/endpoints#get-collectionscollectionidfolders"
          },
          {
            "text": "POST /collections/:collectionId/folders",
            "link": "/endpoints#post-collectionscollectionidfolders"
          },
          {
            "text": "PATCH /folders/:id",
            "link": "/endpoints#patch-foldersid"
          },
          {
            "text": "DELETE /folders/:id",
            "link": "/endpoints#delete-foldersid"
          },
          {
            "text": "PUT /collections/:collectionId/folders/reorder",
            "link": "/endpoints#put-collectionscollectionidfoldersreorder"
          }
        ],
        "collapsed": false
      },
      {
        "text": "Requests",
        "link": "/endpoints#requests",
        "items": [
          {
            "text": "GET /collections/:collectionId/requests",
            "link": "/endpoints#get-collectionscollectionidrequests"
          },
          {
            "text": "POST /collections/:collectionId/requests",
            "link": "/endpoints#post-collectionscollectionidrequests"
          },
          {
            "text": "PUT /requests/:id",
            "link": "/endpoints#put-requestsid"
          },
          {
            "text": "DELETE /requests/:id",
            "link": "/endpoints#delete-requestsid"
          },
          {
            "text": "PUT /collections/:collectionId/requests/reorder",
            "link": "/endpoints#put-collectionscollectionidrequestsreorder"
          },
          {
            "text": "PUT /requests/:id/move",
            "link": "/endpoints#put-requestsidmove"
          }
        ],
        "collapsed": false
      },
      {
        "text": "Documents",
        "link": "/endpoints#documents",
        "items": [
          {
            "text": "GET /collections/:collectionId/documents",
            "link": "/endpoints#get-collectionscollectioniddocuments"
          },
          {
            "text": "POST /collections/:collectionId/documents",
            "link": "/endpoints#post-collectionscollectioniddocuments"
          },
          {
            "text": "PUT /documents/:id",
            "link": "/endpoints#put-documentsid"
          },
          {
            "text": "DELETE /documents/:id",
            "link": "/endpoints#delete-documentsid"
          },
          {
            "text": "PUT /collections/:collectionId/documents/reorder",
            "link": "/endpoints#put-collectionscollectioniddocumentsreorder"
          },
          {
            "text": "PUT /documents/:id/move",
            "link": "/endpoints#put-documentsidmove"
          }
        ],
        "collapsed": false
      },
      {
        "text": "Discussions",
        "link": "/endpoints#discussions",
        "items": [
          {
            "text": "GET /requests/:id/discussions",
            "link": "/endpoints#get-requestsiddiscussions"
          },
          {
            "text": "POST /requests/:id/discussions",
            "link": "/endpoints#post-requestsiddiscussions"
          },
          {
            "text": "Other entity discussion routes",
            "link": "/endpoints#other-entity-discussion-routes"
          },
          {
            "text": "POST /discussion-comments/:id/replies",
            "link": "/endpoints#post-discussion-commentsidreplies"
          },
          {
            "text": "PUT /discussion-comments/:id",
            "link": "/endpoints#put-discussion-commentsid"
          },
          {
            "text": "DELETE /discussion-comments/:id",
            "link": "/endpoints#delete-discussion-commentsid"
          },
          {
            "text": "Thread watches",
            "link": "/endpoints#thread-watches"
          },
          {
            "text": "MLS relay (E2EE hubs)",
            "link": "/endpoints#mls-relay-e2ee-hubs"
          }
        ],
        "collapsed": false
      },
      {
        "text": "LLM routes",
        "link": "/endpoints#llm-routes",
        "items": [
          {
            "text": "GET /llm/models",
            "link": "/endpoints#get-llmmodels"
          },
          {
            "text": "GET /llm/usage",
            "link": "/endpoints#get-llmusage"
          },
          {
            "text": "POST /llm/chat/step",
            "link": "/endpoints#post-llmchatstep"
          },
          {
            "text": "POST /llm/chat/stream",
            "link": "/endpoints#post-llmchatstream"
          }
        ],
        "collapsed": false
      },
      {
        "text": "Plugin sources",
        "link": "/endpoints#plugin-sources",
        "items": [
          {
            "text": "GET /plugins/sources",
            "link": "/endpoints#get-pluginssources"
          }
        ],
        "collapsed": false
      }
    ],
    "collapsed": false
  },
  {
    "text": "Development",
    "link": "/development"
  },
  {
    "text": "Build",
    "link": "/build"
  },
  {
    "text": "Scripts",
    "link": "/scripts"
  },
  {
    "text": "License",
    "link": "/license"
  }
]
