/**
 * Ordered VitePress sidebar manifest for canonical docs pages.
 *
 * Generated by scripts/split-readme.mjs. Edit to reorder nav or add pages.
 * Run `pnpm docs:build:nav` to regenerate the sidebar.
 */

/** @typedef {{ name: string; source: string; title: string; targetDir?: string }} SyncedDocPage */

/** @type {SyncedDocPage[]} Optional synced pages copied from elsewhere in the repo. */
export const syncedPages = [];

/**
 * Top-level docs navigation entries in sidebar order.
 *
 * @type {Array<
 *   | { kind: 'overview'; title: string }
 *   | { kind: 'page'; slug: string; title: string; maxDepth?: number; pinnedBottom?: true }
 *   | { kind: 'group'; slug: string; title: string; pages: SyncedDocPage[]; hideChildren?: boolean }
 * >}
 *
 * A `group` with `hideChildren: true` renders as a single sidebar link to its
 * `/<slug>/` overview page; its child pages stay routable (and link-checked)
 * but are surfaced from the overview page rather than the sidebar.
 */
export const docsNav = [
  { kind: 'overview', title: 'Team Hub' },
  { kind: 'page', slug: 'prerequisites', title: 'Prerequisites', maxDepth: 0 },
  { kind: 'page', slug: 'setup', title: 'Setup', maxDepth: 0 },
  { kind: 'page', slug: 'configuration', title: 'Configuration', maxDepth: 2 },
  {
    kind: 'group',
    slug: 'deploy',
    title: 'Deploy',
    hideChildren: true,
    pages: [
      {
        name: 'docker',
        source: 'docs/deploy/docker.md',
        title: 'Docker Compose'
      },
      {
        name: 'npm',
        source: 'docs/deploy/npm.md',
        title: 'npm CLI'
      },
      {
        name: 'vps',
        source: 'docs/deploy/vps.md',
        title: 'VPS'
      },
      {
        name: 'gcp',
        source: 'docs/deploy/gcp.md',
        title: 'Google Cloud Run'
      },
      {
        name: 'k8s',
        source: 'docs/deploy/k8s.md',
        title: 'Kubernetes'
      }
    ]
  },
  { kind: 'page', slug: 'auth', title: 'Authentication', maxDepth: 0 },
  { kind: 'page', slug: 'llm', title: 'LLM', maxDepth: 2 },
  { kind: 'page', slug: 'ai-chat-stream', title: 'AI chat stream', maxDepth: 2 },
  { kind: 'page', slug: 'cli', title: 'CLI', maxDepth: 2 },
  { kind: 'page', slug: 'endpoints', title: 'API Endpoints', maxDepth: 3 },
  { kind: 'page', slug: 'development', title: 'Development', maxDepth: 0 },
  { kind: 'page', slug: 'build', title: 'Build', maxDepth: 0 },
  { kind: 'page', slug: 'scripts', title: 'Scripts', maxDepth: 0 },
  { kind: 'page', slug: 'license', title: 'License', maxDepth: 0 },
];

/** Slugs of canonical overview pages committed under docs/<slug>/index.md. */
export const groupOverviewSlugs = new Set(
  docsNav.filter((entry) => entry.kind === 'group').map((entry) => entry.slug),
);

/** Slugs of canonical guide pages committed as docs/<slug>.md. */
export const canonicalPageSlugs = new Set(
  docsNav.filter((entry) => entry.kind === 'page').map((entry) => entry.slug),
);
