// Generated by scripts/build-docs-nav.mjs. Do not edit manually.

import type { DefaultTheme } from 'vitepress'

export const sidebar: DefaultTheme.SidebarItem[] = 
[
  {
    "text": "Home",
    "link": "/"
  },
  {
    "text": "Features",
    "link": "/features"
  },
  {
    "text": "Getting started",
    "link": "/getting-started",
    "items": [
      {
        "text": "Download",
        "link": "/getting-started#download"
      },
      {
        "text": "Install on Windows",
        "link": "/getting-started#install-on-windows"
      },
      {
        "text": "Install on macOS",
        "link": "/getting-started#install-on-macos"
      },
      {
        "text": "Install on Linux",
        "link": "/getting-started#install-on-linux"
      },
      {
        "text": "What's next",
        "link": "/getting-started#whats-next"
      }
    ],
    "collapsed": false
  },
  {
    "text": "Request scripts",
    "link": "/request-scripts",
    "items": [
      {
        "text": "Execution order",
        "link": "/request-scripts#execution-order"
      },
      {
        "text": "The hc object",
        "link": "/request-scripts#the-hc-object"
      },
      {
        "text": "console",
        "link": "/request-scripts#console"
      },
      {
        "text": "What gets applied back",
        "link": "/request-scripts#what-gets-applied-back"
      },
      {
        "text": "Sandbox limits",
        "link": "/request-scripts#sandbox-limits"
      },
      {
        "text": "Examples",
        "link": "/request-scripts#examples"
      }
    ],
    "collapsed": false
  },
  {
    "text": "Environments",
    "link": "/environments",
    "items": [
      {
        "text": "Managing environments",
        "link": "/environments#managing-environments"
      },
      {
        "text": "Selecting an environment",
        "link": "/environments#selecting-an-environment"
      },
      {
        "text": "Variables",
        "link": "/environments#variables"
      },
      {
        "text": "Precedence",
        "link": "/environments#precedence"
      },
      {
        "text": "Storage",
        "link": "/environments#storage"
      }
    ],
    "collapsed": false
  }
]
