// Generated by scripts/build-docs-nav.mjs. Do not edit manually.

import type { DefaultTheme } from 'vitepress'

export const sidebar: DefaultTheme.SidebarItem[] = 
[
  {
    "text": "Introduction",
    "link": "/"
  },
  {
    "text": "Installation",
    "link": "/installation"
  },
  {
    "text": "Usage",
    "link": "/usage",
    "items": [
      {
        "text": "Providers",
        "link": "/usage#providers"
      },
      {
        "text": "Lifecycle helpers",
        "link": "/usage#lifecycle-helpers"
      },
      {
        "text": "Product UI vs this package",
        "link": "/usage#product-ui-vs-this-package"
      }
    ],
    "collapsed": false
  },
  {
    "text": "Host API",
    "link": "/host-api",
    "items": [
      {
        "text": "Runtime control",
        "link": "/host-api#runtime-control"
      },
      {
        "text": "Event handlers",
        "link": "/host-api#event-handlers"
      },
      {
        "text": "Logs",
        "link": "/host-api#logs"
      },
      {
        "text": "App factory and ports",
        "link": "/host-api#app-factory-and-ports"
      },
      {
        "text": "Config re-export",
        "link": "/host-api#config-re-export"
      }
    ],
    "collapsed": false
  },
  {
    "text": "Development",
    "link": "/development",
    "items": [
      {
        "text": "Docs",
        "link": "/development#docs"
      }
    ],
    "collapsed": false
  },
  {
    "text": "License",
    "link": "/license"
  }
]
