import { vi, type Mocked } from 'vitest';
import type { IDatabase } from '#/db/IDatabase.js';

/**
 * Stub {@link IDatabase} with unresolved vi.fn mocks for every method.
 *
 * Used by HTTP and CLI tests that only exercise a subset of database behavior.
 *
 * @returns Database stub whose methods can be configured per test.
 */
export function createStubDatabase(): Mocked<IDatabase> {
  const db = {
    connect: vi.fn(),
    disconnect: vi.fn(),
    ping: vi.fn(),
    migrate: vi.fn(),
    getTenantId: vi.fn().mockReturnValue('__default__'),
    forTenant: vi.fn(),
    ensureDefaultTenant: vi.fn(),
    listTenants: vi.fn().mockResolvedValue([]),
    createTenant: vi.fn(),
    findTenantById: vi.fn(),
    updateTenantAvatar: vi.fn(),
    deleteTenant: vi.fn(),
    ensureSystemUser: vi.fn(),
    getSystemUserId: vi.fn().mockReturnValue('system-user-id'),
    listAuditLog: vi.fn().mockResolvedValue([]),
    createUser: vi.fn(),
    findUserById: vi.fn(),
    findUserByName: vi.fn(),
    listUsers: vi.fn().mockResolvedValue([]),
    updateUser: vi.fn(),
    deleteUser: vi.fn(),
    migrateOrphanTokensToBootstrapUser: vi.fn(),
    createApiToken: vi.fn(),
    findActiveApiTokenByHash: vi.fn(),
    listApiTokens: vi.fn(),
    listApiTokensByUserId: vi.fn(),
    findApiTokenById: vi.fn(),
    deleteApiToken: vi.fn(),
    revokeApiToken: vi.fn(),
    touchApiTokenLastUsed: vi.fn(),
    createDeviceKey: vi.fn(),
    findDeviceKeyById: vi.fn(),
    findActiveDeviceKeyByUserAndDeviceId: vi.fn(),
    listDeviceKeysByUserId: vi.fn().mockResolvedValue([]),
    listDeviceKeys: vi.fn().mockResolvedValue([]),
    revokeDeviceKey: vi.fn(),
    touchDeviceKeyLastSeen: vi.fn(),
    getDiscussionMlsGroupState: vi.fn().mockResolvedValue(null),
    upsertDiscussionMlsGroupState: vi.fn(),
    createDiscussionMlsCommit: vi.fn(),
    listDiscussionMlsCommits: vi.fn().mockResolvedValue({ commits: [] }),
    findDiscussionMlsCommitById: vi.fn().mockResolvedValue(null),
    createDiscussionMlsWelcome: vi.fn(),
    listDiscussionMlsWelcomes: vi.fn().mockResolvedValue({ welcomes: [] }),
    findDiscussionMlsWelcomeById: vi.fn().mockResolvedValue(null),
    createInvitedUser: vi.fn(),
    createInvitation: vi.fn(),
    findInvitationById: vi.fn(),
    findInvitationByCodeHash: vi.fn(),
    listInvitations: vi.fn().mockResolvedValue([]),
    revokeInvitation: vi.fn(),
    redeemInvitation: vi.fn(),
    listCollections: vi.fn(),
    createCollection: vi.fn(),
    updateCollection: vi.fn(),
    deleteCollection: vi.fn(),
    findCollectionById: vi.fn(),
    setCollectionDeletionLocked: vi.fn(),
    listEnvironments: vi.fn(),
    createEnvironment: vi.fn(),
    updateEnvironment: vi.fn(),
    deleteEnvironment: vi.fn(),
    findEnvironmentById: vi.fn(),
    setEnvironmentDeletionLocked: vi.fn(),
    listSnippets: vi.fn(),
    createSnippet: vi.fn(),
    updateSnippet: vi.fn(),
    deleteSnippet: vi.fn(),
    findSnippetById: vi.fn(),
    setSnippetDeletionLocked: vi.fn(),
    listLiveServers: vi.fn().mockResolvedValue([]),
    createLiveServer: vi.fn(),
    updateLiveServer: vi.fn(),
    deleteLiveServer: vi.fn(),
    findLiveServerById: vi.fn(),
    setLiveServerDeletionLocked: vi.fn(),
    listLivePages: vi.fn().mockResolvedValue([]),
    createLivePage: vi.fn(),
    updateLivePage: vi.fn(),
    deleteLivePage: vi.fn(),
    findLivePageById: vi.fn(),
    setLivePageDeletionLocked: vi.fn(),
    listRequests: vi.fn(),
    findRequestById: vi.fn(),
    saveRequest: vi.fn(),
    deleteRequest: vi.fn(),
    listFolders: vi.fn(),
    findFolderById: vi.fn(),
    createFolder: vi.fn(),
    renameFolder: vi.fn(),
    deleteFolder: vi.fn(),
    moveFolder: vi.fn(),
    reorderFolders: vi.fn(),
    reorderRequests: vi.fn(),
    moveRequest: vi.fn(),
    listDocuments: vi.fn(),
    findDocumentById: vi.fn(),
    saveDocument: vi.fn(),
    deleteDocument: vi.fn(),
    reorderDocuments: vi.fn(),
    moveDocument: vi.fn(),
    getLlmUsage: vi.fn(),
    addLlmUsage: vi.fn(),
    createLlmUsageLog: vi.fn(),
    listLlmUsageLogs: vi.fn().mockResolvedValue([]),
    listRunResultsForUser: vi.fn().mockResolvedValue([]),
    listAllRunResults: vi.fn().mockResolvedValue([]),
    createRunResult: vi.fn(),
    findRunResultById: vi.fn(),
    deleteRunResult: vi.fn(),
    createDiscussionComment: vi.fn(),
    listDiscussionComments: vi.fn().mockResolvedValue({ comments: [], nextCursor: null }),
    findDiscussionCommentById: vi.fn(),
    updateDiscussionComment: vi.fn(),
    tombstoneDiscussionComment: vi.fn(),
    createNotices: vi.fn().mockResolvedValue([]),
    listNotices: vi.fn().mockResolvedValue({ notices: [], nextCursor: null }),
    countUnreadNotices: vi.fn().mockResolvedValue(0),
    markNoticeRead: vi.fn(),
    markAllNoticesRead: vi.fn().mockResolvedValue(0),
    getUserNotificationSettings: vi.fn().mockResolvedValue({
      userId: 'user-1',
      level: 'all',
      updatedAt: new Date('2026-01-01T00:00:00.000Z')
    }),
    updateUserNotificationSettings: vi.fn(),
    subscribeDiscussionThread: vi
      .fn()
      .mockImplementation(async (userId: string, rootCommentId: string) => ({
        userId,
        rootCommentId,
        createdAt: new Date('2026-01-01T00:00:00.000Z')
      })),
    unsubscribeDiscussionThread: vi.fn(),
    isSubscribedToDiscussionThread: vi.fn().mockResolvedValue(false),
    listDiscussionThreadSubscribers: vi.fn().mockResolvedValue([])
  } as Mocked<IDatabase>;

  db.forTenant.mockImplementation(() => db);
  return db;
}
